# Generated by Django 3.0.3 on 2020-03-04 09:31

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modifieduser',
            managers=[
                ('objects', users.models.ModifiedUserManager()),
            ],
        ),
    ]
