# Generated by Django 3.0.3 on 2020-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0002_auto_20200304_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieduser',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
