# Generated by Django 3.0.3 on 2020-03-14 17:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200315_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifieduser',
            name='location',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
