# Generated by Django 3.0.3 on 2020-03-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200315_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifieduser',
            name='location',
        ),
    ]
