# Generated by Django 3.0.3 on 2020-03-15 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0002_auto_20200315_0056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_auto_20200315_0056'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_posted', models.DateField()),
                ('application_src', models.URLField()),
                ('picture_src', models.URLField(blank=True, null=True)),
                ('interest_fields', models.ManyToManyField(to='interests.Interest')),
                ('recommended_courses', models.ManyToManyField(to='courses.Course')),
                ('required_skills', models.ManyToManyField(to='skills.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField()),
                ('has_applied', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
